// Product Copilot LadybugDB schema scaffold
// Generated by hand from the conceptual ontology in 05-ontology-v0.yaml.
// Purpose: provide a practical LadybugDB-first MVP schema for local-first
// Product Copilot prototyping.
//
// Important modeling note:
// - the ontology is conceptual and can reuse relationship verbs across multiple
//   source/target pairs
// - this executable LadybugDB schema uses endpoint-specific relationship table
//   names where needed so each relationship table stays unambiguous
//
// Scope:
// - covers the current MVP slice used by 07-ladybugdb-query-patterns.cypher
//   and 08-ladybugdb-sample-data.cypher
// - does not yet implement every label and edge from 05-ontology-v0.yaml
//
// Execution note:
// - apply on an empty LadybugDB database
// - extend by adding more node/relationship tables as the Product Copilot graph
//   grows

// -----------------------------------------------------------------------------
// Node tables
// -----------------------------------------------------------------------------
CREATE NODE TABLE Evidence(
  id STRING,
  title STRING,
  status STRING,
  summary STRING,
  confidence STRING,
  review_status STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Claim(
  id STRING,
  title STRING,
  status STRING,
  summary STRING,
  confidence STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Opportunity(
  id STRING,
  title STRING,
  status STRING,
  summary STRING,
  priority STRING,
  confidence STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Outcome(
  id STRING,
  title STRING,
  status STRING,
  metric_definition STRING,
  target_value STRING,
  current_value STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Capability(
  id STRING,
  title STRING,
  status STRING,
  priority STRING,
  owner_team STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Feature(
  id STRING,
  title STRING,
  status STRING,
  priority STRING,
  user_impact STRING,
  summary STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Goal(
  id STRING,
  title STRING,
  status STRING,
  priority STRING,
  owner_team STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Requirement(
  id STRING,
  title STRING,
  status STRING,
  requirement_kind STRING,
  priority STRING,
  risk_level STRING,
  rationale STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE AcceptanceCriterion(
  id STRING,
  title STRING,
  status STRING,
  expression STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Decision(
  id STRING,
  title STRING,
  status STRING,
  rationale STRING,
  owner STRING,
  priority STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Assumption(
  id STRING,
  title STRING,
  status STRING,
  summary STRING,
  confidence STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Service(
  id STRING,
  title STRING,
  status STRING,
  owner_team STRING,
  summary STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE ADR(
  id STRING,
  title STRING,
  status STRING,
  rationale STRING,
  summary STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE WorkPackage(
  id STRING,
  title STRING,
  status STRING,
  work_package_type STRING,
  objective STRING,
  autonomy_level STRING,
  risk_level STRING,
  owner STRING,
  allowed_tools STRING[],
  acceptance_checks STRING[],
  required_permissions STRING[],
  PRIMARY KEY (id)
);

CREATE NODE TABLE Artifact(
  id STRING,
  title STRING,
  status STRING,
  artifact_kind STRING,
  version STRING,
  external_ref STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Gap(
  id STRING,
  title STRING,
  status STRING,
  priority STRING,
  rationale STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Deliverable(
  id STRING,
  title STRING,
  status STRING,
  artifact_kind STRING,
  version STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Plateau(
  id STRING,
  title STRING,
  status STRING,
  version STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Release(
  id STRING,
  title STRING,
  status STRING,
  version STRING,
  owner_team STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Metric(
  id STRING,
  title STRING,
  status STRING,
  metric_kind STRING,
  metric_definition STRING,
  formula STRING,
  current_value STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Incident(
  id STRING,
  title STRING,
  status STRING,
  risk_level STRING,
  owner_team STRING,
  blast_radius STRING,
  PRIMARY KEY (id)
);

CREATE NODE TABLE Postmortem(
  id STRING,
  title STRING,
  status STRING,
  owner_team STRING,
  rationale STRING,
  PRIMARY KEY (id)
);

// -----------------------------------------------------------------------------
// Relationship tables
// -----------------------------------------------------------------------------
CREATE REL TABLE SUPPORTS_CLAIM(FROM Evidence TO Claim);
CREATE REL TABLE IMPLIES_OPPORTUNITY(FROM Claim TO Opportunity);
CREATE REL TABLE PURSUES_OUTCOME(FROM Opportunity TO Outcome);
CREATE REL TABLE REALIZES_OUTCOME(FROM Capability TO Outcome);
CREATE REL TABLE IMPLEMENTS_CAPABILITY(FROM Feature TO Capability);

CREATE REL TABLE ADDRESSES_REQUIREMENT(FROM Feature TO Requirement);
CREATE REL TABLE DRIVES_REQUIREMENT(FROM Goal TO Requirement);
CREATE REL TABLE HAS_ACCEPTANCE(FROM Requirement TO AcceptanceCriterion);
CREATE REL TABLE CREATES_REQUIREMENT(FROM Decision TO Requirement);
CREATE REL TABLE BASED_ON_EVIDENCE(FROM Decision TO Evidence);
CREATE REL TABLE RESOLVES_ASSUMPTION(FROM Decision TO Assumption);
CREATE REL TABLE ALLOCATED_TO_SERVICE(FROM Requirement TO Service);
CREATE REL TABLE DECIDES_SERVICE(FROM ADR TO Service);

CREATE REL TABLE IMPLEMENTS_REQUIREMENT(FROM WorkPackage TO Requirement);
CREATE REL TABLE DEPENDS_ON(FROM WorkPackage TO WorkPackage);
CREATE REL TABLE CHANGES_ARTIFACT(FROM WorkPackage TO Artifact);
CREATE REL TABLE PRODUCES_DELIVERABLE(FROM WorkPackage TO Deliverable);
CREATE REL TABLE ADDRESSED_BY_WORK_PACKAGE(FROM Gap TO WorkPackage);
CREATE REL TABLE REALIZES_PLATEAU(FROM Deliverable TO Plateau);
CREATE REL TABLE PRODUCES_RELEASE(FROM Artifact TO Release);

CREATE REL TABLE MEASURES_SERVICE(FROM Metric TO Service);
CREATE REL TABLE AFFECTS_SERVICE(FROM Incident TO Service);
CREATE REL TABLE ANALYZES_INCIDENT(FROM Postmortem TO Incident);
CREATE REL TABLE CREATES_WORK_PACKAGE(FROM Postmortem TO WorkPackage);

// -----------------------------------------------------------------------------
// Suggested growth path
// -----------------------------------------------------------------------------
// 1. Expand this schema incrementally from 05-ontology-v0.yaml.
// 2. Keep conceptual relation verbs in the ontology, but map them to explicit
//    LadybugDB relationship tables when endpoint sets differ.
// 3. Add COPY FROM pipelines once the node/edge layout stabilizes.
